
package org.catolicasc.acervo.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListagemLivros", targetNamespace = "http://service.acervo.catolicasc.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListagemLivros {


    /**
     * 
     * @return
     *     returns java.util.List<org.catolicasc.acervo.service.Livro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarLIvros", targetNamespace = "http://service.acervo.catolicasc.org/", className = "org.catolicasc.acervo.service.ListarLIvros")
    @ResponseWrapper(localName = "listarLIvrosResponse", targetNamespace = "http://service.acervo.catolicasc.org/", className = "org.catolicasc.acervo.service.ListarLIvrosResponse")
    @Action(input = "http://service.acervo.catolicasc.org/ListagemLivros/listarLIvrosRequest", output = "http://service.acervo.catolicasc.org/ListagemLivros/listarLIvrosResponse")
    public List<Livro> listarLIvros();

}
